name: sanity_checks_pytorch
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9.5
  - cudatoolkit
  - pytorch
  - torchvision
  - matplotlib
  - jupyter
  - captum
  - pillow
  - scikit-image<0.17
