name: sanity_checks_pytorch
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9.5
  - cudatoolkit=11.1.74
  - pytorch=1.9.0
  - torchvision=0.2.2
  - matplotlib=3.3.4
  - jupyter=1.0.0
  - captum=0.4.0
  - pillow=8.3.1
  - scikit-image<0.17
